version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: redis:2.8.19
    environment:
        DJANGO_SETTINGS_MODULE: settings_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - run:
          name: Dependencies
          command: |
            pip install -U pip setuptools
            pip install -r tests_requirements.pip
            python setup.py develop
      - run:
          name: Tests
          command: |
            python setup.py pytest
